nemuTUI/nemu

- pkg/linux/arch/PKGBUILD
- sh/upgrade_db.sh
- src/nm_add_vm.c
- src/nm_core.h
- src/nm_database.c
- src/nm_database.h
- src/nm_form.c
- src/nm_form.h
- src/nm_viewer.c
- src/nm_vm_control.c
Hi!
I would periodically to change type of display of virtual machines. I was release this feature.
Please, check it! 
Thanks!
> Add the ability to change the display type

- CMakeLists.txt
- src/nm_cfg_file.c
- src/nm_utils.c
- src/nm_utils.h
1) Reworked config file, database and vm folder management. Now they can be placed in subfolders in users home directory.
2) Added special DEFAULT value for config file parameters, using which it is possible to fall back to value, stored in nemu binary
> Nm cfg reworked

- src/nm_mon_daemon.c
> nm_mon: use atexit instead of on_exit

- src/nm_ovf_import.c
> ova: fix virtual drive size

- CMakeLists.txt
- pkg/linux/gentoo/nemu-9999.ebuild
- src/nm_cfg_file.c
- src/nm_cfg_file.h
- src/nm_main.c
- src/nm_main_loop.c
- src/nm_viewer.c
- src/nm_vm_control.c
- src/nm_vm_control.h
- src/nm_window.c
VNC and SPICE were pretty stupid features.
Make SPICE default viewer protocol.
Close #112
> conenct: vnc and spice are not features anymore

- src/nm_utils.c
> utils: fix nemu's path search on freebsd

- .github/workflows/checkpatch.yml
- .github/workflows/freebsd.yml
- .github/workflows/linux.yml
- .github/workflows/linux_musl.yml
This typo causes workflow not running in PRs.
> ci: fix type in pull request types

- .github/workflows/linux.yml
- .github/workflows/linux_musl.yml
- ci/images/alpine/Dockerfile
> ci: use checkout action

- src/nm_vm_snapshot.c
- src/nm_window.c
> nemu: fix typos

- .github/workflows/linux.yml
- .github/workflows/linux_musl.yml
This patch fix error:
Semmle autobuild: no supported build system detected.
> ci: codeql must run after configure

- CHANGES
- src/nm_add_vm.c
- test/ova_test.py
- test/vm_test.py
> install: user networking is set by default

- src/nm_hw_info.c
> edit: add macosx total memory info

- CHANGES
- sh/upgrade_db.sh
- src/nm_database.c
- src/nm_database.h
- src/nm_edit_boot.c
- src/nm_form.c
- src/nm_form.h
- src/nm_vm_control.c
- src/nm_window.c
- test/vm_test.py
Add -pflash option support.
Close #65
> boot: flash image support

- CHANGES
- man/nemu.1.in
- sh/nemu.bash
- sh/nemu.zsh
- src/nm_main.c
- src/nm_vm_snapshot.c
- src/nm_vm_snapshot.h
--snap-save <vm-name> --name <snap-name> create snapshot 
--snap-load <vm-name> --name <snap-name> load snapshot 
--snap-del  <vm-name> --name <snap-name> delete snapshot 
--snap-list <vm-name> show snapshots
Close #86, #36
> cli: add snapshots commands

- CHANGES
- sh/upgrade_db.sh
- src/nm_database.c
- src/nm_database.h
- src/nm_viewer.c
- src/nm_vm_control.c
Copy and paste between guest and host.
Close #71
> viewer: spice agent support

- src/nm_form.c
> vga: support none option

- .github/workflows/tests.yml
Tests is failed on buntu-22.04.
Later will investigate why.
> test: use ubuntu-20.04

- src/nm_cfg_file.c
- src/nm_cfg_file.h
- src/nm_core.h
- src/nm_main.c
- src/nm_mon_daemon.c
cfg: bypass config if not exist option
Close #152
> cfg: bypass config if not exist option

- remote_api.txt
- src/nm_edit_vm.c
- src/nm_edit_vm.h
- src/nm_remote_api.c
- src/nm_remote_api.h
> remote_api: add vm_set_settings method

- CMakeLists.txt
- sh/upgrade_db.sh
- src/nm_9p_share.c
- src/nm_add_drive.c
- src/nm_add_vm.c
- src/nm_clone_vm.c
- src/nm_database.c
- src/nm_database.h
- src/nm_edit_boot.c
- src/nm_edit_net.c
- src/nm_edit_vm.c
- src/nm_form.c
- src/nm_lan_settings.c
- src/nm_main.c
- src/nm_main_loop.c
- src/nm_mon_daemon.c
- src/nm_qmp_control.c
- src/nm_remote_api.c
- src/nm_rename_vm.c
- src/nm_svg_map.c
- src/nm_usb_plug.c
- src/nm_viewer.c
- src/nm_vm_control.c
- src/nm_vm_snapshot.c
- src/nm_window.c
- test/vm_test.py
> db: refactoring

- src/nm_edit_net.c
> add_iface: check interface name is set

- CHANGES
- sh/upgrade_db.sh
- src/nm_add_drive.c
- src/nm_add_drive.h
- src/nm_add_vm.c
- src/nm_clone_vm.c
- src/nm_core.h
- src/nm_database.h
- src/nm_form.c
- src/nm_form.h
- src/nm_main_loop.c
- src/nm_ovf_import.c
- src/nm_vm_control.c
- src/nm_vm_snapshot.c
- src/nm_vm_snapshot.h
- src/nm_window.c
- src/nm_window.h
- test/vm_test.py
User can select `raw` or `qcow2` format
Closes #172
> vm: image format type support

- CHANGES
- nemu.cfg.sample
- src/nm_cfg_file.c
- src/nm_cfg_file.h
- src/nm_main_loop.c
- src/nm_qmp_control.c
- src/nm_qmp_control.h
- src/nm_utils.c
- src/nm_utils.h
- src/nm_window.c
Terminal must support kitty graphics protocol.
New config parameters:
[preview]
enabled = 0|1
scale = 0|1
png_path = /path/to/vm.png
> ui: vm preview

- .github/workflows/checkpatch.yml
- .github/workflows/tests.yml
https://github.com/actions/runner-images/issues/11101
> ci: bump ubuntu

- .github/workflows/freebsd.yml
> ci: hide version
